name: Build Snapshot

on:
  push:
    branches-ignore:
      - 'feature/**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Publish
        env:
          IS_MAVEN_PUB: true
          DEPLOY_TO_GITHUB_PACKAGES_URL: https://maven.pkg.github.com/${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew publish -Pversion_snapshot -x test

      - uses: actions/upload-artifact@v4
        with:
          name: Unimined Snapshot Artifacts
          path: ./build/libs/
